// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PaperTrade.Infrastructure.Persistence;

#nullable disable

namespace PaperTrade.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PaperTradeDbContext))]
    [Migration("20261002193451_AddWatchlists")]
    partial class AddWatchlists
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PaperTrade.Domain.Portfolios.Portfolio", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("CashBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("cash_balance");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("InitialBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("initial_balance");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_portfolios");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_portfolios_user_id");

                    b.ToTable("portfolios", null, t =>
                        {
                            t.HasCheckConstraint("ck_portfolios_cash_balance_nonnegative", "cash_balance >= 0");

                            t.HasCheckConstraint("ck_portfolios_initial_balance_nonnegative", "initial_balance >= 0");
                        });
                });

            modelBuilder.Entity("PaperTrade.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("PaperTrade.Domain.Watchlists.Watchlist", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_watchlists");

                    b.HasIndex("UserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_watchlists_user_id_name");

                    b.ToTable("watchlists", (string)null);
                });

            modelBuilder.Entity("PaperTrade.Domain.Watchlists.WatchlistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("symbol");

                    b.Property<Guid>("WatchlistId")
                        .HasColumnType("uuid")
                        .HasColumnName("watchlist_id");

                    b.HasKey("Id")
                        .HasName("pk_watchlist_items");

                    b.HasIndex("WatchlistId", "Symbol")
                        .IsUnique()
                        .HasDatabaseName("ux_watchlist_items_watchlist_id_symbol");

                    b.ToTable("watchlist_items", (string)null);
                });

            modelBuilder.Entity("PaperTrade.Domain.Portfolios.Portfolio", b =>
                {
                    b.HasOne("PaperTrade.Domain.Users.User", "User")
                        .WithOne("Portfolio")
                        .HasForeignKey("PaperTrade.Domain.Portfolios.Portfolio", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_portfolios_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PaperTrade.Domain.Watchlists.Watchlist", b =>
                {
                    b.HasOne("PaperTrade.Domain.Users.User", "User")
                        .WithMany("Watchlists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_watchlists_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PaperTrade.Domain.Watchlists.WatchlistItem", b =>
                {
                    b.HasOne("PaperTrade.Domain.Watchlists.Watchlist", "Watchlist")
                        .WithMany("Items")
                        .HasForeignKey("WatchlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_watchlist_items_watchlists_watchlist_id");

                    b.Navigation("Watchlist");
                });

            modelBuilder.Entity("PaperTrade.Domain.Users.User", b =>
                {
                    b.Navigation("Portfolio");

                    b.Navigation("Watchlists");
                });

            modelBuilder.Entity("PaperTrade.Domain.Watchlists.Watchlist", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
