// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PaperTrade.Infrastructure.Persistence;

#nullable disable

namespace PaperTrade.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PaperTradeDbContext))]
    [Migration("20261003203223_AddAlertsAndNotifications")]
    partial class AddAlertsAndNotifications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PaperTrade.Domain.Alerts.PriceAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("direction");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("symbol");

                    b.Property<decimal>("TargetPrice")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("target_price");

                    b.Property<DateTimeOffset?>("TriggeredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("triggered_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_price_alerts");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_price_alerts_user_id");

                    b.HasIndex("IsActive", "Symbol")
                        .HasDatabaseName("ix_price_alerts_active_symbol");

                    b.ToTable("price_alerts", null, t =>
                        {
                            t.HasCheckConstraint("ck_price_alerts_target_price_positive", "target_price > 0");
                        });
                });

            modelBuilder.Entity("PaperTrade.Domain.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_notifications_user_id_created_at");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("PaperTrade.Domain.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ExecutedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at");

                    b.Property<decimal?>("ExecutedPrice")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("executed_price");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("quantity");

                    b.Property<decimal>("RequestedPrice")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("requested_price");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("side");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("status");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("symbol");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("PortfolioId", "CreatedAt")
                        .HasDatabaseName("ix_orders_portfolio_id_created_at");

                    b.ToTable("orders", null, t =>
                        {
                            t.HasCheckConstraint("ck_orders_executed_price_positive", "executed_price IS NULL OR executed_price > 0");

                            t.HasCheckConstraint("ck_orders_quantity_positive", "quantity > 0");

                            t.HasCheckConstraint("ck_orders_requested_price_positive", "requested_price > 0");
                        });
                });

            modelBuilder.Entity("PaperTrade.Domain.Portfolios.Portfolio", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("CashBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("cash_balance");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("InitialBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("initial_balance");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("RealizedPnl")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("realized_pnl");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_portfolios");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_portfolios_user_id");

                    b.ToTable("portfolios", null, t =>
                        {
                            t.HasCheckConstraint("ck_portfolios_cash_balance_nonnegative", "cash_balance >= 0");

                            t.HasCheckConstraint("ck_portfolios_initial_balance_nonnegative", "initial_balance >= 0");
                        });
                });

            modelBuilder.Entity("PaperTrade.Domain.Positions.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AverageEntryPrice")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("average_entry_price");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("quantity");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("symbol");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_positions");

                    b.HasIndex("PortfolioId", "Symbol")
                        .IsUnique()
                        .HasDatabaseName("ux_positions_portfolio_id_symbol");

                    b.ToTable("positions", null, t =>
                        {
                            t.HasCheckConstraint("ck_positions_average_entry_price_positive", "average_entry_price > 0");

                            t.HasCheckConstraint("ck_positions_quantity_positive", "quantity > 0");
                        });
                });

            modelBuilder.Entity("PaperTrade.Domain.Trades.Trade", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ExecutedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_id");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("price");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("quantity");

                    b.Property<decimal>("RealizedPnl")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("realized_pnl");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("side");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("symbol");

                    b.Property<decimal>("TotalValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_value");

                    b.HasKey("Id")
                        .HasName("pk_trades");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("ux_trades_order_id");

                    b.HasIndex("PortfolioId", "ExecutedAt")
                        .HasDatabaseName("ix_trades_portfolio_id_executed_at");

                    b.ToTable("trades", null, t =>
                        {
                            t.HasCheckConstraint("ck_trades_price_positive", "price > 0");

                            t.HasCheckConstraint("ck_trades_quantity_positive", "quantity > 0");

                            t.HasCheckConstraint("ck_trades_total_value_positive", "total_value > 0");
                        });
                });

            modelBuilder.Entity("PaperTrade.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("PaperTrade.Domain.Watchlists.Watchlist", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_watchlists");

                    b.HasIndex("UserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_watchlists_user_id_name");

                    b.ToTable("watchlists", (string)null);
                });

            modelBuilder.Entity("PaperTrade.Domain.Watchlists.WatchlistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("symbol");

                    b.Property<Guid>("WatchlistId")
                        .HasColumnType("uuid")
                        .HasColumnName("watchlist_id");

                    b.HasKey("Id")
                        .HasName("pk_watchlist_items");

                    b.HasIndex("WatchlistId", "Symbol")
                        .IsUnique()
                        .HasDatabaseName("ux_watchlist_items_watchlist_id_symbol");

                    b.ToTable("watchlist_items", (string)null);
                });

            modelBuilder.Entity("PaperTrade.Domain.Alerts.PriceAlert", b =>
                {
                    b.HasOne("PaperTrade.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_price_alerts_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PaperTrade.Domain.Notifications.Notification", b =>
                {
                    b.HasOne("PaperTrade.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PaperTrade.Domain.Orders.Order", b =>
                {
                    b.HasOne("PaperTrade.Domain.Portfolios.Portfolio", "Portfolio")
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_orders_portfolios_portfolio_id");

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("PaperTrade.Domain.Portfolios.Portfolio", b =>
                {
                    b.HasOne("PaperTrade.Domain.Users.User", "User")
                        .WithOne("Portfolio")
                        .HasForeignKey("PaperTrade.Domain.Portfolios.Portfolio", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_portfolios_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PaperTrade.Domain.Positions.Position", b =>
                {
                    b.HasOne("PaperTrade.Domain.Portfolios.Portfolio", "Portfolio")
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_positions_portfolios_portfolio_id");

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("PaperTrade.Domain.Trades.Trade", b =>
                {
                    b.HasOne("PaperTrade.Domain.Orders.Order", "Order")
                        .WithOne()
                        .HasForeignKey("PaperTrade.Domain.Trades.Trade", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trades_orders_order_id");

                    b.HasOne("PaperTrade.Domain.Portfolios.Portfolio", "Portfolio")
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trades_portfolios_portfolio_id");

                    b.Navigation("Order");

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("PaperTrade.Domain.Watchlists.Watchlist", b =>
                {
                    b.HasOne("PaperTrade.Domain.Users.User", "User")
                        .WithMany("Watchlists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_watchlists_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PaperTrade.Domain.Watchlists.WatchlistItem", b =>
                {
                    b.HasOne("PaperTrade.Domain.Watchlists.Watchlist", "Watchlist")
                        .WithMany("Items")
                        .HasForeignKey("WatchlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_watchlist_items_watchlists_watchlist_id");

                    b.Navigation("Watchlist");
                });

            modelBuilder.Entity("PaperTrade.Domain.Users.User", b =>
                {
                    b.Navigation("Portfolio");

                    b.Navigation("Watchlists");
                });

            modelBuilder.Entity("PaperTrade.Domain.Watchlists.Watchlist", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
