// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PaperTrade.Infrastructure.Persistence;

#nullable disable

namespace PaperTrade.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PaperTradeDbContext))]
    partial class PaperTradeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PaperTrade.Domain.Alerts.PriceAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("direction");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("instrument_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("symbol");

                    b.Property<decimal>("TargetPrice")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("target_price");

                    b.Property<DateTimeOffset?>("TriggeredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("triggered_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_price_alerts");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_price_alerts_user_id");

                    b.HasIndex("IsActive", "Symbol")
                        .HasDatabaseName("ix_price_alerts_active_symbol");

                    b.ToTable("price_alerts", null, t =>
                        {
                            t.HasCheckConstraint("ck_price_alerts_target_price_positive", "target_price > 0");
                        });
                });

            modelBuilder.Entity("PaperTrade.Domain.Instruments.Instrument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssetClass")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("asset_class");

                    b.Property<string>("BaseCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("base_currency");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("exchange");

                    b.Property<bool>("IsTradable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_tradable");

                    b.Property<string>("MarketTimeZone")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("market_time_zone");

                    b.Property<decimal>("MinimumOrderSize")
                        .HasPrecision(18, 10)
                        .HasColumnType("numeric(18,10)")
                        .HasColumnName("minimum_order_size");

                    b.Property<int>("PricePrecision")
                        .HasColumnType("integer")
                        .HasColumnName("price_precision");

                    b.Property<int>("QuantityPrecision")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_precision");

                    b.Property<string>("QuoteCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("quote_currency");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("symbol");

                    b.Property<decimal>("TickSize")
                        .HasPrecision(18, 10)
                        .HasColumnType("numeric(18,10)")
                        .HasColumnName("tick_size");

                    b.Property<string>("TradingSession")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("trading_session");

                    b.HasKey("Id")
                        .HasName("pk_instruments");

                    b.HasIndex("Symbol")
                        .IsUnique()
                        .HasDatabaseName("ux_instruments_symbol");

                    b.ToTable("instruments", null, t =>
                        {
                            t.HasCheckConstraint("ck_instruments_minimum_order_size_positive", "minimum_order_size > 0");

                            t.HasCheckConstraint("ck_instruments_tick_size_positive", "tick_size > 0");
                        });
                });

            modelBuilder.Entity("PaperTrade.Domain.Instruments.ProviderSymbol", b =>
                {
                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("instrument_id");

                    b.Property<string>("Provider")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("provider");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("symbol");

                    b.HasKey("InstrumentId", "Provider")
                        .HasName("pk_provider_symbols");

                    b.HasIndex("Provider", "Symbol")
                        .IsUnique()
                        .HasDatabaseName("ux_provider_symbols_provider_symbol");

                    b.ToTable("provider_symbols", (string)null);
                });

            modelBuilder.Entity("PaperTrade.Domain.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_notifications_user_id_created_at");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("PaperTrade.Domain.Orders.Order", b =>
                {
                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ExecutedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at");

                    b.Property<decimal?>("ExecutedPrice")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("executed_price");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<decimal>("FilledQuantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("filled_quantity");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("instrument_id");

                    b.Property<Guid?>("ParentOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_order_id");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("quantity");

                    b.Property<decimal>("RequestedPrice")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("requested_price");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("side");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("symbol");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("ParentOrderId")
                        .HasDatabaseName("ix_orders_parent_order_id");

                    b.HasIndex("PortfolioId", "CreatedAt")
                        .HasDatabaseName("ix_orders_portfolio_id_created_at");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_orders_status_created_at");

                    b.ToTable("orders", null, t =>
                        {
                            t.HasCheckConstraint("ck_orders_filled_quantity_range", "filled_quantity >= 0 AND filled_quantity <= quantity");

                            t.HasCheckConstraint("ck_orders_executed_price_positive", "executed_price IS NULL OR executed_price > 0");

                            t.HasCheckConstraint("ck_orders_quantity_positive", "quantity > 0");

                            t.HasCheckConstraint("ck_orders_requested_price_positive", "requested_price > 0");
                        });
                });

            modelBuilder.Entity("PaperTrade.Domain.Portfolios.EquitySnapshot", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
                    b.Property<decimal>("Cash").HasPrecision(18, 2).HasColumnType("numeric(18,2)").HasColumnName("cash");
                    b.Property<decimal>("Equity").HasPrecision(18, 2).HasColumnType("numeric(18,2)").HasColumnName("equity");
                    b.Property<Guid>("PortfolioId").HasColumnType("uuid").HasColumnName("portfolio_id");
                    b.Property<DateTimeOffset>("RecordedAt").HasColumnType("timestamp with time zone").HasColumnName("recorded_at");
                    b.Property<decimal>("RealizedPnl").HasPrecision(18, 2).HasColumnType("numeric(18,2)").HasColumnName("realized_pnl");
                    b.Property<decimal>("UnrealizedPnl").HasPrecision(18, 2).HasColumnType("numeric(18,2)").HasColumnName("unrealized_pnl");
                    b.HasKey("Id").HasName("pk_equity_snapshots");
                    b.HasIndex("PortfolioId", "RecordedAt").HasDatabaseName("ix_equity_snapshots_portfolio_id_recorded_at");
                    b.ToTable("equity_snapshots", (string)null);
                });

            modelBuilder.Entity("PaperTrade.Domain.Portfolios.Portfolio", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("CashBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("cash_balance");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("InitialBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("initial_balance");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("RealizedPnl")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("realized_pnl");

                    b.Property<decimal?>("MaxDailyLossPercent")
                        .HasPrecision(5, 2).HasColumnType("numeric(5,2)")
                        .HasColumnName("max_daily_loss_percent");

                    b.Property<decimal?>("MaxPositionConcentrationPercent")
                        .HasPrecision(5, 2).HasColumnType("numeric(5,2)")
                        .HasColumnName("max_position_concentration_percent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_portfolios");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_portfolios_user_id");

                    b.ToTable("portfolios", null, t =>
                        {
                            t.HasCheckConstraint("ck_portfolios_cash_balance_nonnegative", "cash_balance >= 0");

                            t.HasCheckConstraint("ck_portfolios_initial_balance_nonnegative", "initial_balance >= 0");
                            t.HasCheckConstraint("ck_portfolios_max_daily_loss_percent", "max_daily_loss_percent IS NULL OR (max_daily_loss_percent > 0 AND max_daily_loss_percent <= 100)");
                            t.HasCheckConstraint("ck_portfolios_max_concentration_percent", "max_position_concentration_percent IS NULL OR (max_position_concentration_percent > 0 AND max_position_concentration_percent <= 100)");
                        });
                });

            modelBuilder.Entity("PaperTrade.Domain.Positions.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AverageEntryPrice")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("average_entry_price");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("instrument_id");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("quantity");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("symbol");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_positions");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("PortfolioId", "InstrumentId")
                        .IsUnique()
                        .HasDatabaseName("ux_positions_portfolio_id_instrument_id");

                    b.ToTable("positions", null, t =>
                        {
                            t.HasCheckConstraint("ck_positions_average_entry_price_positive", "average_entry_price > 0");

                            t.HasCheckConstraint("ck_positions_quantity_positive", "quantity > 0");
                        });
                });

            modelBuilder.Entity("PaperTrade.Domain.TradingJournal.JournalEntry", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
                    b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                    b.Property<string>("Note").IsRequired().HasMaxLength(4000).HasColumnType("character varying(4000)").HasColumnName("note");
                    b.Property<Guid>("OrderId").HasColumnType("uuid").HasColumnName("order_id");
                    b.Property<Guid>("PortfolioId").HasColumnType("uuid").HasColumnName("portfolio_id");
                    b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("timestamp with time zone").HasColumnName("updated_at");
                    b.HasKey("Id").HasName("pk_journal_entries");
                    b.HasIndex("OrderId").IsUnique().HasDatabaseName("ux_journal_entries_order_id");
                    b.HasIndex("PortfolioId").HasDatabaseName("ix_journal_entries_portfolio_id");
                    b.ToTable("journal_entries", (string)null);
                });

            modelBuilder.Entity("PaperTrade.Domain.Trades.Trade", b =>
                {
                    b.Property<decimal>("Fee")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("fee");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ExecutedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("instrument_id");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_id");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("price");

                    b.Property<decimal>("QuotePrice")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("quote_price");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("quantity");

                    b.Property<decimal>("RealizedPnl")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("realized_pnl");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("side");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("symbol");

                    b.Property<decimal>("TotalValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_value");

                    b.HasKey("Id")
                        .HasName("pk_trades");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_trades_order_id");

                    b.HasIndex("PortfolioId", "ExecutedAt")
                        .HasDatabaseName("ix_trades_portfolio_id_executed_at");

                    b.ToTable("trades", null, t =>
                        {
                            t.HasCheckConstraint("ck_trades_fee_nonnegative", "fee >= 0");

                            t.HasCheckConstraint("ck_trades_price_positive", "price > 0");

                            t.HasCheckConstraint("ck_trades_quantity_positive", "quantity > 0");

                            t.HasCheckConstraint("ck_trades_total_value_positive", "total_value > 0");
                        });
                });

            modelBuilder.Entity("PaperTrade.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("PaperTrade.Domain.Watchlists.Watchlist", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_watchlists");

                    b.HasIndex("UserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_watchlists_user_id_name");

                    b.ToTable("watchlists", (string)null);
                });

            modelBuilder.Entity("PaperTrade.Domain.Watchlists.WatchlistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("instrument_id");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("symbol");

                    b.Property<Guid>("WatchlistId")
                        .HasColumnType("uuid")
                        .HasColumnName("watchlist_id");

                    b.HasKey("Id")
                        .HasName("pk_watchlist_items");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("WatchlistId", "InstrumentId")
                        .IsUnique()
                        .HasDatabaseName("ux_watchlist_items_watchlist_id_instrument_id");

                    b.ToTable("watchlist_items", (string)null);
                });

            modelBuilder.Entity("PaperTrade.Domain.Alerts.PriceAlert", b =>
                {
                    b.HasOne("PaperTrade.Domain.Instruments.Instrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_price_alerts_instruments_instrument_id");

                    b.HasOne("PaperTrade.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_price_alerts_users_user_id");

                    b.Navigation("Instrument");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PaperTrade.Domain.Instruments.ProviderSymbol", b =>
                {
                    b.HasOne("PaperTrade.Domain.Instruments.Instrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_provider_symbols_instruments_instrument_id");

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("PaperTrade.Domain.Notifications.Notification", b =>
                {
                    b.HasOne("PaperTrade.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PaperTrade.Domain.Orders.Order", b =>
                {
                    b.HasOne("PaperTrade.Domain.Orders.Order", null)
                        .WithMany()
                        .HasForeignKey("ParentOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_orders_orders_parent_order_id");

                    b.HasOne("PaperTrade.Domain.Instruments.Instrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_orders_instruments_instrument_id");

                    b.HasOne("PaperTrade.Domain.Portfolios.Portfolio", "Portfolio")
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_orders_portfolios_portfolio_id");

                    b.Navigation("Instrument");

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("PaperTrade.Domain.Portfolios.EquitySnapshot", b =>
                {
                    b.HasOne("PaperTrade.Domain.Portfolios.Portfolio", "Portfolio")
                        .WithMany().HasForeignKey("PortfolioId").OnDelete(DeleteBehavior.Cascade)
                        .IsRequired().HasConstraintName("fk_equity_snapshots_portfolios_portfolio_id");
                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("PaperTrade.Domain.Portfolios.Portfolio", b =>
                {
                    b.HasOne("PaperTrade.Domain.Users.User", "User")
                        .WithOne("Portfolio")
                        .HasForeignKey("PaperTrade.Domain.Portfolios.Portfolio", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_portfolios_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PaperTrade.Domain.Positions.Position", b =>
                {
                    b.HasOne("PaperTrade.Domain.Instruments.Instrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_positions_instruments_instrument_id");

                    b.HasOne("PaperTrade.Domain.Portfolios.Portfolio", "Portfolio")
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_positions_portfolios_portfolio_id");

                    b.Navigation("Instrument");

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("PaperTrade.Domain.TradingJournal.JournalEntry", b =>
                {
                    b.HasOne("PaperTrade.Domain.Orders.Order", null).WithMany()
                        .HasForeignKey("OrderId").OnDelete(DeleteBehavior.Cascade).IsRequired()
                        .HasConstraintName("fk_journal_entries_orders_order_id");
                    b.HasOne("PaperTrade.Domain.Portfolios.Portfolio", null).WithMany()
                        .HasForeignKey("PortfolioId").OnDelete(DeleteBehavior.Cascade).IsRequired()
                        .HasConstraintName("fk_journal_entries_portfolios_portfolio_id");
                });

            modelBuilder.Entity("PaperTrade.Domain.Trades.Trade", b =>
                {
                    b.HasOne("PaperTrade.Domain.Instruments.Instrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_trades_instruments_instrument_id");

                    b.HasOne("PaperTrade.Domain.Orders.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trades_orders_order_id");

                    b.HasOne("PaperTrade.Domain.Portfolios.Portfolio", "Portfolio")
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trades_portfolios_portfolio_id");

                    b.Navigation("Instrument");

                    b.Navigation("Order");

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("PaperTrade.Domain.Watchlists.Watchlist", b =>
                {
                    b.HasOne("PaperTrade.Domain.Users.User", "User")
                        .WithMany("Watchlists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_watchlists_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PaperTrade.Domain.Watchlists.WatchlistItem", b =>
                {
                    b.HasOne("PaperTrade.Domain.Instruments.Instrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_watchlist_items_instruments_instrument_id");

                    b.HasOne("PaperTrade.Domain.Watchlists.Watchlist", "Watchlist")
                        .WithMany("Items")
                        .HasForeignKey("WatchlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_watchlist_items_watchlists_watchlist_id");

                    b.Navigation("Instrument");

                    b.Navigation("Watchlist");
                });

            modelBuilder.Entity("PaperTrade.Domain.Users.User", b =>
                {
                    b.Navigation("Portfolio");

                    b.Navigation("Watchlists");
                });

            modelBuilder.Entity("PaperTrade.Domain.Watchlists.Watchlist", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
